var sitedata = {
	"sitewide": {
		"footerText": "&copy; M. Roberts <span></span>",
		"missionText": "",
		"menuItems": [
			{
				"menuItem": "View All Hot Springs",
				"menuItemURL": "/fulllist.html"
			},
            {
				"menuItem": "About",
				"menuItemURL": "/about.html"
			}
		]
	},
	"index": {
		"headerText": "Hot Springs",
		"headerSpanText": "Handbook",
		"pageTitle": "",
		"headerLink": "../",
		"featured": {
			"featuredHeader": "Featured Hot Springs",
			"featuredCondensedName": "mountainvillageresort"
		},
		"sectionHeaders": {
			"mostPopHeader": "Most Popular Hot Springs",
			"highRateHeader": "Highest Rated Hot Springs"
		},
        "fallback": "snakepit"
	},
	"fullListAndMap": {
		"fullListHeader": "All Hot Springs"
	},
	"activites": [
		{
	
			"hotsprings": [
				{
					"index": {
						"headerText": "Hot Springs",
						"headerSpanText": "Handbook",
						"headerLink": "../",
						"fallback": "snakepit",
						"featuredName": "snakepit"
					},
					"springs": [
                        {
							"name": "Boat Box Hot Springs",
							"condensedName": "boatbox",
							"type": "hotsprings",
							"nearestTown": "Stanley, ID",
							"region": "stanley",
							"state": "idaho",
							"rating": 86,
							"description": "One of the only hot springs that you can act like you're being cooked alive by giants!",
							"longdescription": "<p>Also known as Elkhorn Hot Springs. If you can get here when there are no other cars waiting it'll be a miracle, but it's well worth the attempt if you're heading this direction. To get here, drive North out of Stanley for about 12 miles and keep an eye out for a pullout on the right.  </p><p>Arriving at Boatbox you'll look down the embankment toward the river a few feet and see a large metal tub that looks more like a kettle than a bath tub. The tub fits 2-3 comfortably and 4-5 if you're close. There are some smaller rock pools at the river, but we know what you're really there for! Excruciating cold!</p><p>There are often cars waiting, so get in line, try again later, and don't be a jerk; the people before you probably have only been soaking for 5 minutes.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>If you can, definitely try this one out, if only for the novelty factor. It makes for a great photo op to make all your friends jealous, and forget how insignificant we all really are!</p>",
							"parkingCost": "None",
							"walkingDist": "50 Feet",
							"easeOfAccess": 15,
							"accessableSeasons": "All",
							"elevation": "6100",
							"waterTemp": "Adjustable",
							"peopleMeter": 85,
							"nudity": "Negative",
							"website": "",
							"popular": true,
							"textTop": "textTop",
							"commercial": false,
							"latitude": 44.259174,
							"longitude": -114.834611,
							"zoom": 9,
							"images": {
								"thumbImg" : "4",
								"mobileBackPos": "left center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Bonneville Hot Springs",
							"condensedName": "bonneville",
							"type": "hotsprings",
							"nearestTown": "Lowman, ID",
							"region": "gardenvalley",
							"state": "idaho",
							"rating": 60,
							"description": "Nestled amongst a decent size campground, this spring comes out scalding hot and mixing with sweet sweet cold water is a must.",
							"longdescription": "<p>When first arriving, watch for campers on the way in. They're squirrelly. The trailhead for the spring is located at the end of Bonneville Campground. At the trailhead you'll pay for parking and then start the short and level, but pretty, hike into the springs.</p><p><b>Be careful once you get to the springs, the water is hot enough to burn you easily in certain spots. Don’t step into the flowing water without checking first.</b></p><p> During the winter you'll have to park at the entrance and snowshoe in, which can be fun, but be prepared! As always, watch yourself when in the backcountry in winter.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>Many people love this hot spring, but my experience while not bad, wasn't relaxing as we spent the whole time trying to mix the water so we weren't being burned alive. This was in summer, so it could be completely different in winter!</p>",
							"parkingCost": "$5",
							"walkingDist": ".3 Miles - 1.1 Miles",
							"easeOfAccess": 50,
							"accessableSeasons": "All",
							"elevation": "4700",
							"waterTemp": "Extremely Hot - Very Cold",
							"peopleMeter": 75,
							"nudity": "Only when it's cold. Like, really cold.",
							"website": "",
							"popular": true,
							"textTop": "textTop",
							"commercial": false,
							"latitude": 44.157184,
							"longitude": -115.314394,
							"zoom": 9,
							"images": {
								"thumbImg" : "5",
								"mobileBackPos": "left center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Goldbug Hot Springs",
							"condensedName": "goldbug",
							"type": "hotsprings",
							"nearestTown": "Challis, ID",
							"region": "salmon",
							"state": "idaho",
							"rating": 75,
							"description": "The hike to the spring is tough, but worth it if you can get there when there's not a crowd.",
							"longdescription": "<p>Also known as Elk Bend Hot Springs. To get to Goldbug Hot Springs is fairly simple, you’ll park at the end of Warn Springs Rd near Salmon, ID. There is a posted trailhead for the hot springs there. From there follow the hot springs, up and up. You’ll pass through a couple gates, over private land, so be respectful. Once back on public land, stop being respectiful, and continue up the mountain. Be prepared for a good strenuous hike, across rock fields and up switchbacks. It’s not impossible by any means, I nearly died from being out of shape. Near the top are some awesome pools formed by the stream that are worth looking at, the area is beautiful!</p><p>During the summer the crowds come in waves, and during a recent August visit there were probably 25 people at the springs. That's not to say it wasn't worth it, but definitely be willing to share at this springs.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>Be in decent shape, better than me at least. Or be willing to take lots of breaks and enjoy the views.</p>",
							"parkingCost": "None",
							"walkingDist": "1.75 Miles",
							"easeOfAccess": 75,
							"accessableSeasons": "Spring, Summer, Fall",
							"elevation": "6200",
							"waterTemp": "Warm/Hot",
							"peopleMeter": 90,
							"nudity": "Bring a swimsuit, but be prepared to see others in all their glory.",
							"website": "",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude": 44.905398,
							"longitude": -113.929643,
							"zoom": 9,
							"images": {
								"thumbImg" : "1",
								"mobileBackPos": "left center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Kirkham Hot Springs",
							"condensedName": "kirkham",
							"type": "hotsprings",
							"nearestTown": "Lowman, ID",
							"region": "gardenvalley",
							"state": "idaho",
							"rating": 95,
							"description": "One of the coolest springs in the country, but also one of the closest to Boise. You do the math on crowds.",
							"longdescription": "<p>Whenever someone says they haven't been to a hot springs before, this is where you take them. Access to the springs is easy (only a small hill to walk down), the water is always an amazing temperature, and the soaking is second to none. There are waterfalls of hot spring water to stand under for god's sake! There are several pools to choose from, and come late fall even more appear before the water gets too high in the spring.</p><p>That being said, the hot springs is located next to a summer opened campground and the number of visitors to this spring are higher than ever.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>Time it right, don't go on long weekends, and you can have an amazing personal soak that other states only wished they had.</p>",
							"parkingCost": "$5",
							"walkingDist": ".1 Miles",
							"easeOfAccess": 10,
							"accessableSeasons": "All",
							"elevation": "3936",
							"waterTemp": "104-112",
							"peopleMeter": 90,
							"nudity": "In plain view of highway. And maybe a nunnery.",
							"website": "",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude" : 44.072611,
							"longitude": -115.545602,
							"zoom": 9,
							"images": {
								"thumbImg" : "11",
								"mobileBackPos": "bottom center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Mountain Village Resort Hot Springs",
							"condensedName": "mountainvillageresort",
							"type": "hotsprings",
							"nearestTown": "Stanley, ID",
							"region": "stanley",
							"state": "idaho",
							"rating": 91,
							"description": "A personal favorite, this spring is reserved for the guests of the Mountain Village Resort in Stanley, ID.",
							"longdescription": "<p>Upon Arriving at the Mountain Village Resort you can check in and reserve a time for the private hot springs. Offered free of charge to guests, the spring is inside of a small building with a couple changing rooms and benches. Right now, they allow up to 8 people in at a time, so please share the spaces.</p><p>The views from this hot springs are incredible, as you can open a side of the building and the Sawtooths are right there to welcome you.",
                            "personalNotes": "<p><b>Personal Note: </b>I’ve been in this spring when it was 50 degrees out and -10 degrees out. Every time the water temperature is amazing. Though the short walk back can be a literal killer when it’s super cold out, so bundle up!</p>",
							"parkingCost": "None",
							"walkingDist": ".25",
							"easeOfAccess": 20,
							"accessableSeasons": "All",
							"elevation": "6258",
							"waterTemp": "106",
							"peopleMeter": 85,
							"nudity": "I mean... you could",
							"website": "http://www.mountainvillage.com/services/hot-spring/",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": true,
							"latitude" : 44.221100,
							"longitude": -114.931407,
							"zoom": 9,
							"images": {
								"thumbImg" : "10",
								"mobileBackPos": "left center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Sacejewea Hot Springs",
							"condensedName": "sacejewea",
							"type": "hotsprings",
							"nearestTown": "Lowman, ID",
							"region": "gardenvalley",
							"state": "idaho",
							"rating": 70,
							"description": "Off the beaten path, Sacejewea sits in a slight valley with views of the Sawtooths that most people don't ever see.",
							"longdescription": "<p>Getting to this hot springs is pretty simple. Head towards Stanley on the road from Lowman, and take a right onto a dirt road right before the avalanche gates. The springs is within yelling distance of Grandjean, Idaho. Park where you can and head down the hill to take in the sights.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>Last time I was here it was -14 degrees out in the morning, but the day before it was a nice soak, though somewhat shallow.</p>",
							"parkingCost": "None",
							"walkingDist": "",
							"easeOfAccess": 25,
							"accessableSeasons": "All",
							"elevation": "5085",
							"waterTemp": "104",
							"peopleMeter": 30,
							"nudity": "It's possible you'll see some twigs and berries here.",
							"website": "",
							"popular": false,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude" : 44.160305,
							"longitude": -115.178106,
							"zoom": 9,
							"images": {
								"thumbImg" : "4",
								"mobileBackPos": "center center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Sunbeam Hot Springs",
							"condensedName": "sunbeam",
							"type": "hotsprings",
							"nearestTown": "Stanley, ID",
							"region": "stanley",
							"state": "idaho",
							"rating": 80,
							"description": "Surrounded with more history than other springs, but being right on the highway attracts everyone to take a soak.",
							"longdescription": "<p>Getting to Sunbeam Hot Springs couldn't be easier. Head North out of Stanley, and when you see a ton of steam on both sides of the road with 'Low Visibility' signs, you know you're there. There is a large pull out area and an outhouse. Be sure to walk around the old stone bathhouse and get a feel for the area before heading down to the water. The walk down is short, and except for one part where there is a large step down, very easy.</p><p><b>The water coming down the hill is hot enough to instantly burn you, do not try and cross it or jump in it, and any water you do get into, test the temperature first!</b> I've seen first hand here someone step into a pool and not be very happy about it.</p>",
                            "personalNotes": "<p>Sunbeam is a hot spring I go back and forth on. When I've been here with just my own people, it's amazing, but having to share means having to find spots where you're not being scaled and not freezing, which become few and far between in the winter months. It's definitely worth a soak, but with so many others nearby, maybe try them if it's super busy here.</p>",
							"parkingCost": "None",
							"walkingDist": ".1 Miles",
							"easeOfAccess": 15,
							"accessableSeasons": "All",
							"elevation": "5943",
							"waterTemp": "104-112",
							"peopleMeter": 75,
							"nudity": "Don't you do it!",
							"website": "",
							"popular": true,
							"textTop": "textBottom",
							"siteURL": "",
							"commercial": false,
							"latitude" : 44.267574,
							"longitude": -114.749786,
							"zoom": 9,
							"images": {
								"thumbImg" : "3",
								"mobileBackPos": "left center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "The Springs",
							"condensedName": "thesprings",
							"type": "hotsprings",
							"nearestTown": "Idaho City, ID",
							"region": "boise",
							"state": "idaho",
							"rating": 75,
							"description": "Probably the nicest hot spring in the state as far as luxury goes, The Springs is a family friendly destination with curious rules and high prices.",
							"longdescription": "<p>The Springs has been a favorite for weekend trips and some weeknight getaways since they reopened several years ago. Head up towards Idaho City from Boise, and it's on the left right before town. They have several private pools for rent, a large open main pool, and a steaming hot tub. They limit the amount of people let in at a time as well, so it's usually not too crowded.</p><p>They do have strange rules regarding alcohol (1 drink per hour), and seem to raise their prices at any opportunity (currently $17 for each adult, and $45 for a private pool for an hour). I usually plan on spending $80 everytime I come here. That being said, it's hard to get this quality of a soak in within an hour of the city in any direction, the staff is very friendly, and the facilities are awesome, so it can definitely be worth it sometimes.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>The sign for The Springs is terribly underlit, so if driving there at night keep a close eye out for it before you hit Idaho City. I've been there several times and still have to push the brakes to turn harder than I like to.</p>",
							"parkingCost": "None",
							"walkingDist": "Parking Lot to Doors",
							"easeOfAccess": 5,
							"accessableSeasons": "All",
							"elevation": "3845",
							"waterTemp": "104-112",
							"peopleMeter": 85,
							"nudity": "Negative, Ghost Rider",
							"website": "http://www.thespringsid.com/",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": true,
							"latitude" : 43.815556,
							"longitude": -115.864566,
							"zoom": 9,
							"images": {
								"thumbImg" : "6",
								"mobileBackPos": "left center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Trail Creek Hot Springs",
							"condensedName": "trailcreek",
							"type": "hotsprings",
							"nearestTown": "McCall, ID",
							"region": "mccall",
							"state": "idaho",
							"rating": 85,
							"description": "Far enough away from the major highway to be somewhat semi-private, this is one of the best handmade pools in the state.",
							"longdescription": "<p>Another personal favorite, Trail Creek is a wonderful soak if you can get there when not many people are around, which isn't as hard as it seems.</p><p>To get there, head up towards McCall from Boise, turn right, right after the bridge in Cascade and drive for 19.4 miles where you'll see a pull out on the right side of the road on a bend. The trail should be pretty obvious.</p><p><b>While very short, this trail is steep and extremely treacherous in the winter, be prepared!</b> Once at the bottom, a bridge made from a couple boards crosses the rushing stream and connects to the first of two pools. The other pool is upstream 20-30 yards. Both pool have great water, and people have made some amazing pools there over the years. You should be easily able to sit down in them and not be cold in the winter.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>I've been here in the summer and winter, and both are amazing times, especially in the middle of the night when the stars just go nuts.</p>",
							"parkingCost": "None",
							"walkingDist": ".1 Miles",
							"easeOfAccess": 60,
							"accessableSeasons": "All",
							"elevation": "5500",
							"waterTemp": "104-112",
							"peopleMeter": 50,
							"nudity": "Let er' hang out, just keep a suit handy!",
							"website": "",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude" : 44.627074,
							"longitude": -115.749786,
							"zoom": 9,
							"images": {
								"thumbImg" : "5",
								"mobileBackPos": "left center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Snake Pit Hot Springs",
							"condensedName": "snakepit",
							"type": "hotsprings",
							"nearestTown": "Stanley, ID",
							"region": "stanley",
							"state": "idaho",
							"rating": 70,
							"description": "Seemingly little known gem, located right in the backyard of Stanley, Idaho.",
							"longdescription": "<p>Also known as Sawtooth View Hot Springs, which may be the better name, as the views from this hot spring are insane. To get to Snake Pit, head north like you're leaving Stanley but just before the end of town turn left into the Stanley Museum parking lot. Head to the back of the dirt lot and continue on down the road. Drive about .4 miles and you'll see a dirt lot on the left which you may need a 4x4 to get over a little berm to get into. From there, cross the long narrow bridge by the parking area and the hot springs is to the left by the river. </p><p>Our experience was a great one, but this hot springs is very silty, so keep that in mind. Just don't move much and you'll be fine! The hot water comes right out the ground, which is a real treat to sit on.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>Seriously, go here. If only to start off a day of hot springing, it's a great way to kick things off. Probably only good in the summerish times, as it was a little colder.</p>",
							"parkingCost": "None",
							"walkingDist": ".1 Miles",
							"easeOfAccess": 25,
							"accessableSeasons": "Late Spring, Summer, Early Fall",
							"elevation": "6249",
							"waterTemp": "96-102",
							"peopleMeter": 60,
							"nudity": "Maybe with a suit handy, but still in the middle of town",
							"website": "",
							"popular": false,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude" : 44.221876,
							"longitude": -114.931162,
							"zoom": 9,
							"images": {
								"thumbImg" : "5",
								"mobileBackPos": "center center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Basin Creek Campground Hot Springs",
							"condensedName": "basincreek",
							"type": "hotsprings",
							"nearestTown": "Stanley, ID",
							"region": "stanley",
							"state": "idaho",
							"rating": 40,
							"description": "Roadside springs with bathroom and lukewarm water",
							"longdescription": "<p>Basin Creek Campground is just around the bend from this hot spring north of Stanley. You'll turn on a dirt road to the left and go a couple hundred yards (road is probably impassable in the winter).</p>",
                            "personalNotes": "<p><b>Personal Note: </b>Didn't make the trek down the side of the hill for this one, as it looked just 'meh'.</p>",
							"parkingCost": "None",
							"walkingDist": ".1",
							"easeOfAccess": 50,
							"accessableSeasons": "All",
							"elevation": "6100",
							"waterTemp": "Hot",
							"peopleMeter": 30,
							"nudity": "",
							"website": "",
							"popular": false,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude" : 44.264257,
							"longitude": -114.820155,
							"zoom": 9,
							"images": {
								"thumbImg" : "2",
								"mobileBackPos": "center center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Cove Hot Springs",
							"condensedName": "covecreek",
							"type": "hotsprings",
							"nearestTown": "Stanley, ID",
							"region": "stanley",
							"state": "idaho",
							"rating": 40,
                            "description": "Roadside springs with bathroom and lukewarm water",
							"longdescription": "<p>Also known as Basin Creek Hot Springs. Basin Creek Hot Springs seems to be one of those ones that people want to love, but it's never really going to be hot enough to love as much as you could. Kind of like Megan from High School, you know the one.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>Granted the last time here was in the winter, the pools were far too shallow and the water too cold to soak. It's a nice spot, so maybe trying again in summer is called for.</p>",
							"parkingCost": "None",
							"walkingDist": ".1",
							"easeOfAccess": 40,
							"accessableSeasons": "All",
							"elevation": "6100",
							"waterTemp": "88ish",
							"peopleMeter": 30,
							"nudity": "Nah, too much shrinkage.",
							"website": "",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude" : 44.264190,
							"longitude": -114.811716,
							"zoom": 9,
							"images": {
								"thumbImg" : "3",
								"mobileBackPos": "center center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Snively Hot Springs",
							"condensedName": "snively",
							"type": "hotsprings",
							"nearestTown": "Ontario, ID",
							"region": "eastOregon",
							"state": "oregon",
							"rating": 65,
							"description": "Although in another state, this hot spring is easy to get to, a super pretty drive, and during the summer would be a pretty huge pool.",
							"longdescription": "<p>Late summer or early fall would be the best time to take a trip to Snively Hot Springs. The river runs high other times of year and makes the large pool considerably smaller. This, mixed with searing hot water, makes for a day of trying to get the mixture correct enough to sit in for awhile.</p>",
                            "personalNotes": "<p><b>Personal Note: </b>A fun summer day trip, I'd wait for a nice fall day to check this bad boy out.</p>",
							"parkingCost": "None",
							"walkingDist": ".1",
							"easeOfAccess": 15,
							"accessableSeasons": "All",
							"elevation": "2400",
							"waterTemp": "Hot Hot Hot",
							"peopleMeter": 70,
							"nudity": "Iffy, I'd probably stay suited",
							"website": "",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": false,
							"latitude" : 43.730288,
							"longitude": -117.203095,
							"zoom": 9,
							"images": {
								"thumbImg" : "2",
								"mobileBackPos": "center center",
								"imgPath": "/activities/hotsprings/"
							}
						},
						{
							"name": "Miracle Hot Springs",
							"condensedName": "miracle",
							"type": "hotsprings",
							"nearestTown": "Hagerman, ID",
							"region": "southernIdaho",
							"state": "idaho",
							"rating": 65,
							"description": "Super busy, but clean, this spring is perfect for families and groups.",
							"longdescription": "<p>Getting to Miracle Hot Springs is easy; head to Hagerman from Boise, pass through Hagerman, and drive through the beautiful valley area to finally find the springs on the right.</p><p>Be aware that the amount of people here seems to be unregulated, so it's often extremely full. They do offer private tub rooms that fit a couple to several people that are cleaned after each use, so this is really the only way to have any privacy. The main pools are great for families and those who don't mind the crowds. Private rooms are clean, but in the beginning stages of disrepair. Worth the time for a fun day trip!</p>",
                            "personalNotes": "<p><b>Personal Note: </b> Not a great place for romance, but a fun trip for established couples or families.</p>",
							"parkingCost": "None",
							"walkingDist": ".1",
							"easeOfAccess": 5,
							"accessableSeasons": "All",
							"elevation": "5000",
							"waterTemp": "Warm to Hot",
							"peopleMeter": 100,
							"nudity": "Oh my, please no.",
							"website": "http://miraclehotspring.com/",
							"popular": true,
							"textTop": "textTop",
							"siteURL": "",
							"commercial": true,
							"latitude" : 42.694383,
							"longitude": -114.856602,
							"zoom": 9,
							"images": {
								"thumbImg" : "3",
								"mobileBackPos": "center center",
								"imgPath": "/activities/hotsprings/"
							}
						}
					]
				}
			]
		}
	]
};
var featuredData,
    activity,
    all,
    snapshot = Defiant.getSnapshot(sitedata);
function activityData(name) {
    activity = JSON.search(snapshot, "//*[contains(condensedName, '" + name + "')]");
}